// Fitness Machine Service
export const FTMS_SERVICE_UUID = 0x1826
export const INDOOR_BIKE_DATA_UUID = 0x2AD2
export const FITNESS_MACHINE_FEATURE_UUID = 0x2ACC
export const FITNESS_MACHINE_STATUS_UUID = 0x2ADA

// Indoor Bike Data フラグ（bit 0 が 0 のとき instantaneous speed が存在する）
export const IBD_FLAG = {
  MORE_DATA:                     1 << 0,
  AVERAGE_SPEED_PRESENT:         1 << 1,
  INSTANTANEOUS_CADENCE_PRESENT: 1 << 2,
  AVERAGE_CADENCE_PRESENT:       1 << 3,
  TOTAL_DISTANCE_PRESENT:        1 << 4,
  RESISTANCE_LEVEL_PRESENT:      1 << 5,
  INSTANTANEOUS_POWER_PRESENT:   1 << 6,
  AVERAGE_POWER_PRESENT:         1 << 7,
  EXPENDED_ENERGY_PRESENT:       1 << 8,
  HEART_RATE_PRESENT:            1 << 9,
  METABOLIC_EQUIVALENT_PRESENT:  1 << 10,
  ELAPSED_TIME_PRESENT:          1 << 11,
  REMAINING_TIME_PRESENT:        1 << 12,
}

// Cycling Power Service
export const CPS_SERVICE_UUID = 0x1818
export const CYCLING_POWER_MEASUREMENT_UUID = 0x2A63
export const CYCLING_POWER_FEATURE_UUID = 0x2A65
export const SENSOR_LOCATION_UUID = 0x2A5D

// Cycling Power Measurement フラグ
export const CPM_FLAG = {
  PEDAL_POWER_BALANCE_PRESENT:    1 << 0,
  PEDAL_POWER_BALANCE_REFERENCE:  1 << 1,
  ACCUMULATED_TORQUE_PRESENT:     1 << 2,
  ACCUMULATED_TORQUE_SOURCE:      1 << 3,
  WHEEL_REVOLUTION_DATA_PRESENT:  1 << 4,
  CRANK_REVOLUTION_DATA_PRESENT:  1 << 5,
  EXTREME_FORCE_MAGNITUDES_PRESENT:  1 << 6,
  EXTREME_TORQUE_MAGNITUDES_PRESENT: 1 << 7,
  EXTREME_ANGLES_PRESENT:         1 << 8,
  TOP_DEAD_SPOT_ANGLE_PRESENT:    1 << 9,
  BOTTOM_DEAD_SPOT_ANGLE_PRESENT: 1 << 10,
  ACCUMULATED_ENERGY_PRESENT:     1 << 11,
  OFFSET_COMPENSATION_INDICATOR:  1 << 12,
}

// Heart Rate Service
export const HRS_SERVICE_UUID = 0x180D
export const HEART_RATE_MEASUREMENT_UUID = 0x2A37
